'use client';

import { useAuth } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import { useState, useEffect } from "react";
import { marked } from "marked";
import markedKatex from "marked-katex-extension";
import "katex/dist/contrib/mhchem";

interface Note {
  _id: string;
  title: string;
  description: string;
  content: string;
  createdAt: string;
  status: string;
  originalFileName?: string;
}

export default function NotePage({
  params
}: {
  params: Promise<{ id: string }>
}) {
  const { isLoaded, isSignedIn } = useAuth();
  const router = useRouter();
  const [note, setNote] = useState<Note | null>(null);
  const [loading, setLoading] = useState(true);
  const [showTranscript, setShowTranscript] = useState(false);
  const [transcript, setTranscript] = useState<string | null>(null);
  const [transcriptLoading, setTranscriptLoading] = useState(false);
  const [transcriptAutoGenerated, setTranscriptAutoGenerated] = useState(false);

  useEffect(() => {
    // Import mhchem extension for chemical equations
    const loadMhchem = async () => {
      try {
        // @ts-ignore - mhchem extension doesn't have TypeScript declarations but works
        await import('katex/contrib/mhchem');
      } catch (e) {
        console.warn('Could not load mhchem extension:', e);
      }
    };
    loadMhchem();

    // Configure marked with KaTeX extension
    marked.use(markedKatex({
      throwOnError: false,
      output: 'html'
    }));

    const initPage = async () => {
      if (isLoaded && !isSignedIn) {
        router.push('/');
        return;
      }

      if (isLoaded && isSignedIn) {
        fetchNote();
      }
    };

    initPage();
  }, [isLoaded, isSignedIn]);

  const fetchNote = async () => {
    try {
      const { id } = await params;
      const response = await fetch(`/api/notes/${id}`);
      if (response.ok) {
        const data = await response.json();
        setNote(data);
      } else if (response.status === 404) {
        router.push('/');
      }
    } catch (error) {
      console.error('Failed to fetch note:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteNote = async () => {
    if (!confirm('Are you sure you want to delete this note?')) {
      return;
    }

    try {
      const { id } = await params;
      const response = await fetch(`/api/notes/${id}`, {
        method: 'DELETE',
      });
      if (response.ok) {
        router.push('/');
      }
    } catch (error) {
      console.error('Failed to delete note:', error);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const fetchTranscript = async () => {
    if (transcript !== null) return;
    
    setTranscriptLoading(true);
    try {
      const { id } = await params;
      const response = await fetch(`/api/notes/${id}/transcript`);
      if (response.ok) {
        const text = await response.text();
        setTranscript(text);
        // Check if transcript is same as content (auto-generated from older notes)
        if (note && text === note.content) {
          setTranscriptAutoGenerated(true);
        }
      } else {
        setTranscript('');
      }
    } catch (error) {
      console.error('Failed to fetch transcript:', error);
      setTranscript('');
    } finally {
      setTranscriptLoading(false);
    }
  };

  const toggleTranscript = () => {
    if (!showTranscript && transcript === null) {
      fetchTranscript();
    }
    setShowTranscript(!showTranscript);
  };

  const downloadMarkdown = () => {
    if (!note) return;
    
    const blob = new Blob([note.content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyMarkdown = async () => {
    if (!note) return;
    
    try {
      await navigator.clipboard.writeText(note.content);
      alert('Markdown copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy markdown:', error);
      alert('Failed to copy to clipboard');
    }
  };

  const downloadTranscript = () => {
    if (!transcript) return;
    
    const blob = new Blob([transcript], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note?.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_transcript.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyTranscript = async () => {
    if (!transcript) return;
    
    try {
      await navigator.clipboard.writeText(transcript);
      alert('Transcript copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy transcript:', error);
      alert('Failed to copy to clipboard');
    }
  };

  if (!isLoaded || loading) {
    return (
      <div className="container">
        <div className="card">
          <p>Loading...</p>
        </div>
      </div>
    );
  }

  if (!isSignedIn) {
    return null;
  }

  if (!note) {
    return (
      <div className="container">
        <div className="card">
          <p>Note not found.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container">
      <div style={{ marginBottom: '20px', display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' }}>
        <button onClick={() => router.back()} className="btn btn-secondary">
          ← Back
        </button>
        <button onClick={deleteNote} className="btn btn-danger">
          Delete Note
        </button>
        <div style={{ flex: 1 }} />
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <button onClick={downloadMarkdown} className="btn btn-primary">
            ↓ Download MD
          </button>
          <button onClick={copyMarkdown} className="btn btn-secondary">
            📋 Copy MD
          </button>
          <button 
            onClick={toggleTranscript} 
            className={`btn ${showTranscript ? 'btn-primary' : 'btn-secondary'}`}
          >
            {showTranscript ? '✕ Hide Transcript' : '👁 Show Transcript'}
          </button>
          {transcript !== null && (
            <>
              <button onClick={downloadTranscript} className="btn btn-primary">
                ↓ Save TXT
              </button>
              <button onClick={copyTranscript} className="btn btn-secondary">
                📋 Copy TXT
              </button>
            </>
          )}
        </div>
      </div>

      <div className="card">
        <header style={{ marginBottom: '30px', borderBottom: '1px solid #e2e8f0', paddingBottom: '20px' }}>
          <h1 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '10px' }}>
            {note.title}
          </h1>
          <p style={{ color: '#6b7280', fontSize: '16px', marginBottom: '10px' }}>
            {note.description}
          </p>
          <p style={{ color: '#9ca3af', fontSize: '14px' }}>
            Created on {formatDate(note.createdAt)}
          </p>
        </header>

        {note.status === 'processing' ? (
          <div style={{ textAlign: 'center', padding: '40px' }}>
            <p>This note is still being processed. Please check back in a few minutes.</p>
          </div>
        ) : (
          <div
            className="markdown-content"
            dangerouslySetInnerHTML={{ __html: marked(note.content) }}
          />
        )}

        {showTranscript && (
          <div style={{ marginTop: '30px', borderTop: '1px solid #e2e8f0', paddingTop: '20px' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 'bold', marginBottom: '15px' }}>
              Original Transcript
            </h2>
            {transcriptLoading ? (
              <p>Loading transcript...</p>
            ) : transcript ? (
              <>
                {transcriptAutoGenerated && (
                  <div style={{ 
                    marginBottom: '15px', 
                    padding: '12px', 
                    backgroundColor: '#fef3c7', 
                    border: '1px solid #f59e0b',
                    borderRadius: '6px',
                    fontSize: '14px',
                    color: '#92400e'
                  }}>
                    ℹ️ This note was created before transcript storage was added. The transcript has been auto-generated from the note content.
                  </div>
                )}
                <div 
                  className="card"
                  style={{ 
                    backgroundColor: '#f8fafc', 
                    padding: '20px',
                    whiteSpace: 'pre-wrap',
                    fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                    fontSize: '14px',
                    lineHeight: '1.6',
                    maxHeight: '500px',
                    overflowY: 'auto'
                  }}
                >
                  {transcript}
                </div>
              </>
            ) : (
              <p>No transcript available for this note.</p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
