'use client';

import { useAuth } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import { useState, useEffect } from "react";
import { marked } from "marked";
import markedKatex from "marked-katex-extension";
import "katex/dist/contrib/mhchem";

interface Note {
  _id: string;
  title: string;
  description: string;
  content: string;
  createdAt: string;
  status: string;
  originalFileName?: string;
  flashcards: Flashcard[];
  quizQuestions: QuizQuestion[];
}

interface Flashcard {
  front: string;
  back: string;
}

interface QuizQuestion {
  question: string;
  wrongAnswers: string[];
  correctAnswer: string;
  explanation: string;
}

export default function NotePage({
  params
}: {
  params: Promise<{ id: string }>
}) {
  const { isLoaded, isSignedIn } = useAuth();
  const router = useRouter();
  const [note, setNote] = useState<Note | null>(null);
  const [loading, setLoading] = useState(true);
  const [showTranscript, setShowTranscript] = useState(false);
  const [transcript, setTranscript] = useState<string | null>(null);
  const [transcriptLoading, setTranscriptLoading] = useState(false);
  const [transcriptAutoGenerated, setTranscriptAutoGenerated] = useState(false);
  const [showStudyMode, setShowStudyMode] = useState(false);
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [currentFlashcardIndex, setCurrentFlashcardIndex] = useState(-1);
  const [flashcardFlipped, setFlashcardFlipped] = useState(false);
  const [currentQuizIndex, setCurrentQuizIndex] = useState(-1);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [quizCompleted, setQuizCompleted] = useState(false);

  useEffect(() => {
    // Import mhchem extension for chemical equations
    const loadMhchem = async () => {
      try {
        // @ts-ignore - mhchem extension doesn't have TypeScript declarations but works
        await import('katex/contrib/mhchem');
      } catch (e) {
        console.warn('Could not load mhchem extension:', e);
      }
    };
    loadMhchem();

    // Configure marked with KaTeX extension
    marked.use(markedKatex({
      throwOnError: false,
      output: 'html'
    }));

    const initPage = async () => {
      if (isLoaded && !isSignedIn) {
        router.push('/');
        return;
      }

      if (isLoaded && isSignedIn) {
        fetchNote();
      }
    };

    initPage();
  }, [isLoaded, isSignedIn]);

  const fetchNote = async () => {
    try {
      const { id } = await params;
      const response = await fetch(`/api/notes/${id}`);
      if (response.ok) {
        const data = await response.json();
        setNote(data);
        setFlashcards(data.flashcards || []);
        setQuizQuestions(data.quizQuestions || []);
        // Initialize indices if data exists
        if (data.flashcards?.length > 0) {
          setCurrentFlashcardIndex(0);
        }
        if (data.quizQuestions?.length > 0) {
          setCurrentQuizIndex(0);
        }
      } else if (response.status === 404) {
        router.push('/');
      }
    } catch (error) {
      console.error('Failed to fetch note:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteNote = async () => {
    if (!confirm('Are you sure you want to delete this note?')) {
      return;
    }

    try {
      const { id } = await params;
      const response = await fetch(`/api/notes/${id}`, {
        method: 'DELETE',
      });
      if (response.ok) {
        router.push('/');
      }
    } catch (error) {
      console.error('Failed to delete note:', error);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const fetchTranscript = async () => {
    if (transcript !== null) return;
    
    setTranscriptLoading(true);
    try {
      const { id } = await params;
      const response = await fetch(`/api/notes/${id}/transcript`);
      if (response.ok) {
        const text = await response.text();
        setTranscript(text);
        // Check if transcript is same as content (auto-generated from older notes)
        if (note && text === note.content) {
          setTranscriptAutoGenerated(true);
        }
      } else {
        setTranscript('');
      }
    } catch (error) {
      console.error('Failed to fetch transcript:', error);
      setTranscript('');
    } finally {
      setTranscriptLoading(false);
    }
  };

  const toggleTranscript = () => {
    if (!showTranscript && transcript === null) {
      fetchTranscript();
    }
    setShowTranscript(!showTranscript);
  };

  const downloadMarkdown = () => {
    if (!note) return;
    
    const blob = new Blob([note.content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyMarkdown = async () => {
    if (!note) return;
    
    try {
      await navigator.clipboard.writeText(note.content);
      alert('Markdown copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy markdown:', error);
      alert('Failed to copy to clipboard');
    }
  };

  const downloadTranscript = () => {
    if (!transcript) return;
    
    const blob = new Blob([transcript], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note?.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_transcript.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyTranscript = async () => {
    if (!transcript) return;
    
    try {
      await navigator.clipboard.writeText(transcript);
      alert('Transcript copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy transcript:', error);
      alert('Failed to copy to clipboard');
    }
  };

  const toggleStudyMode = () => {
    setShowStudyMode(!showStudyMode);
    if (!showStudyMode) {
      // Reset indices when opening
      if (flashcards.length > 0 && currentFlashcardIndex === -1) {
        setCurrentFlashcardIndex(0);
      }
      if (quizQuestions.length > 0 && currentQuizIndex === -1) {
        setCurrentQuizIndex(0);
      }
    }
  };

  const toggleFlashcard = () => {
    setFlashcardFlipped(!flashcardFlipped);
  };

  const nextFlashcard = () => {
    if (currentFlashcardIndex < flashcards.length - 1) {
      setCurrentFlashcardIndex(currentFlashcardIndex + 1);
      setFlashcardFlipped(false);
    }
  };

  const prevFlashcard = () => {
    if (currentFlashcardIndex > 0) {
      setCurrentFlashcardIndex(currentFlashcardIndex - 1);
      setFlashcardFlipped(false);
    }
  };

  const getRandomizedAnswers = (question: QuizQuestion) => {
    const answers = [
      { text: question.correctAnswer, isCorrect: true },
      ...question.wrongAnswers.map(a => ({ text: a, isCorrect: false }))
    ];
    return answers.sort(() => Math.random() - 0.5);
  };

  const selectQuizAnswer = (index: number) => {
    setSelectedAnswer(index);
  };

  const nextQuizQuestion = () => {
    if (currentQuizIndex < quizQuestions.length - 1) {
      setCurrentQuizIndex(currentQuizIndex + 1);
      setSelectedAnswer(null);
    } else {
      setQuizCompleted(true);
    }
  };

  const restartQuiz = () => {
    setCurrentQuizIndex(0);
    setSelectedAnswer(null);
    setQuizCompleted(false);
  };

  const downloadFlashcards = () => {
    const content = JSON.stringify(flashcards, null, 2);
    const blob = new Blob([content], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note?.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_flashcards.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const downloadQuiz = () => {
    const content = JSON.stringify(quizQuestions, null, 2);
    const blob = new Blob([content], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note?.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_quiz.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (!isLoaded || loading) {
    return (
      <div className="container">
        <div className="card">
          <p>Loading...</p>
        </div>
      </div>
    );
  }

  if (!isSignedIn) {
    return null;
  }

  if (!note) {
    return (
      <div className="container">
        <div className="card">
          <p>Note not found.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container">
      <div style={{ marginBottom: '20px', display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' }}>
        <button onClick={() => router.back()} className="btn btn-secondary">
          ← Back
        </button>
        <button onClick={deleteNote} className="btn btn-danger">
          Delete Note
        </button>
        <div style={{ flex: 1 }} />
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <button onClick={downloadMarkdown} className="btn btn-primary">
            ↓ Download MD
          </button>
          <button onClick={copyMarkdown} className="btn btn-secondary">
            📋 Copy MD
          </button>
          <button 
            onClick={toggleTranscript} 
            className={`btn ${showTranscript ? 'btn-primary' : 'btn-secondary'}`}
          >
            {showTranscript ? '✕ Hide Transcript' : '👁 Show Transcript'}
          </button>
          {transcript !== null && (
            <>
              <button onClick={downloadTranscript} className="btn btn-primary">
                ↓ Save TXT
              </button>
              <button onClick={copyTranscript} className="btn btn-secondary">
                📋 Copy TXT
              </button>
            </>
          )}
          <button 
            onClick={toggleStudyMode} 
            className={`btn ${showStudyMode ? 'btn-primary' : 'btn-secondary'}`}
            disabled={flashcards.length === 0 && quizQuestions.length === 0}
          >
            {showStudyMode ? '✕ Hide Study' : '🎴 Study Mode'}
          </button>
        </div>
      </div>

      <div className="card">
        <header style={{ marginBottom: '30px', borderBottom: '1px solid #e2e8f0', paddingBottom: '20px' }}>
          <h1 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '10px' }}>
            {note.title}
          </h1>
          <p style={{ color: '#6b7280', fontSize: '16px', marginBottom: '10px' }}>
            {note.description}
          </p>
          <p style={{ color: '#9ca3af', fontSize: '14px' }}>
            Created on {formatDate(note.createdAt)}
          </p>
        </header>

        {note.status === 'processing' ? (
          <div style={{ textAlign: 'center', padding: '40px' }}>
            <p>This note is still being processed. Please check back in a few minutes.</p>
          </div>
        ) : (
          <div
            className="markdown-content"
            dangerouslySetInnerHTML={{ __html: marked(note.content) }}
          />
        )}

        {showTranscript && (
          <div style={{ marginTop: '30px', borderTop: '1px solid #e2e8f0', paddingTop: '20px' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 'bold', marginBottom: '15px' }}>
              Original Transcript
            </h2>
            {transcriptLoading ? (
              <p>Loading transcript...</p>
            ) : transcript ? (
              <>
                {transcriptAutoGenerated && (
                  <div style={{ 
                    marginBottom: '15px', 
                    padding: '12px', 
                    backgroundColor: '#fef3c7', 
                    border: '1px solid #f59e0b',
                    borderRadius: '6px',
                    fontSize: '14px',
                    color: '#92400e'
                  }}>
                    ℹ️ This note was created before transcript storage was added. The transcript has been auto-generated from the note content.
                  </div>
                )}
                <div 
                  className="card"
                  style={{ 
                    backgroundColor: '#f8fafc', 
                    padding: '20px',
                    whiteSpace: 'pre-wrap',
                    fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                    fontSize: '14px',
                    lineHeight: '1.6',
                    maxHeight: '500px',
                    overflowY: 'auto'
                  }}
                >
                  {transcript}
                </div>
              </>
            ) : (
              <p>No transcript available for this note.</p>
            )}
          </div>
        )}

        {showStudyMode && (
          <div style={{ marginTop: '30px', borderTop: '1px solid #e2e8f0', paddingTop: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h2 style={{ fontSize: '1.5rem', fontWeight: 'bold' }}>
                Study Materials
              </h2>
              <div style={{ display: 'flex', gap: '8px' }}>
                <button onClick={downloadFlashcards} className="btn btn-secondary" disabled={flashcards.length === 0}>
                  ↓ Save Cards
                </button>
                <button onClick={downloadQuiz} className="btn btn-secondary" disabled={quizQuestions.length === 0}>
                  ↓ Save Quiz
                </button>
              </div>
            </div>

            {/* Tabs for Flashcards and Quiz */}
            <div style={{ display: 'flex', gap: '8px', marginBottom: '20px' }}>
              <button 
                onClick={() => {
                  if (flashcards.length > 0) {
                    setCurrentFlashcardIndex(0);
                    setCurrentQuizIndex(-1);
                    setFlashcardFlipped(false);
                  }
                }} 
                className={`btn ${currentQuizIndex === -1 && flashcards.length > 0 ? 'btn-primary' : 'btn-secondary'}`}
                style={{ flex: 1 }}
                disabled={flashcards.length === 0}
              >
                🎴 Flashcards ({flashcards.length})
              </button>
              <button 
                onClick={() => {
                  if (quizQuestions.length > 0) {
                    setCurrentQuizIndex(0);
                    setCurrentFlashcardIndex(-1);
                    setSelectedAnswer(null);
                  }
                }} 
                className={`btn ${currentFlashcardIndex === -1 && quizQuestions.length > 0 ? 'btn-primary' : 'btn-secondary'}`}
                style={{ flex: 1 }}
                disabled={quizQuestions.length === 0}
              >
                📝 Quiz ({quizQuestions.length})
              </button>
            </div>

            {/* Flashcards Section */}
            {currentQuizIndex === -1 && flashcards.length > 0 && currentFlashcardIndex >= 0 && currentFlashcardIndex < flashcards.length && (
              <div>
                <div style={{ marginBottom: '15px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span>Card {currentFlashcardIndex + 1} of {flashcards.length}</span>
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <button onClick={prevFlashcard} disabled={currentFlashcardIndex === 0} className="btn btn-secondary">
                      ← Previous
                    </button>
                    <button onClick={nextFlashcard} disabled={currentFlashcardIndex >= flashcards.length - 1} className="btn btn-secondary">
                      Next →
                    </button>
                  </div>
                </div>
                <div 
                  onClick={toggleFlashcard}
                  style={{ 
                    minHeight: '200px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    textAlign: 'center',
                    padding: '40px',
                    backgroundColor: flashcardFlipped ? '#dbeafe' : '#f8fafc',
                    border: '2px solid #3b82f6',
                    borderRadius: '12px',
                    cursor: 'pointer',
                    fontSize: '18px',
                    lineHeight: '1.6',
                    transition: 'all 0.2s'
                  }}
                >
                  <div>
                    <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '10px' }}>
                      {flashcardFlipped ? 'Answer' : 'Question'}
                    </div>
                    {flashcardFlipped ? flashcards[currentFlashcardIndex]?.back : flashcards[currentFlashcardIndex]?.front}
                    <div style={{ fontSize: '12px', color: '#9ca3af', marginTop: '15px' }}>
                      Click to flip
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Quiz Section */}
            {currentFlashcardIndex === -1 && quizQuestions.length > 0 && currentQuizIndex >= 0 && currentQuizIndex < quizQuestions.length && (
              <div>
                {!quizCompleted ? (
                  <>
                    <div style={{ marginBottom: '15px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <span>Question {currentQuizIndex + 1} of {quizQuestions.length}</span>
                    </div>
                    <div className="card" style={{ backgroundColor: '#f8fafc', padding: '30px' }}>
                      <h3 style={{ fontSize: '18px', fontWeight: '600', marginBottom: '20px' }}>
                        {quizQuestions[currentQuizIndex]?.question || 'No question available'}
                      </h3>
                      <div style={{ display: 'grid', gap: '10px' }}>
                        {(() => {
                          const currentQ = quizQuestions[currentQuizIndex];
                          if (!currentQ) return null;
                          const randomizedAnswers = getRandomizedAnswers(currentQ);
                          return randomizedAnswers.map((answer, index) => (
                            <button
                              key={index}
                              onClick={() => selectQuizAnswer(index)}
                              style={{
                                padding: '15px 20px',
                                textAlign: 'left',
                                backgroundColor: selectedAnswer === index ? '#dbeafe' : 'white',
                                border: selectedAnswer === index ? '2px solid #3b82f6' : '2px solid #e2e8f0',
                                borderRadius: '8px',
                                cursor: 'pointer',
                                fontSize: '15px',
                                transition: 'all 0.2s'
                              }}
                            >
                              {String.fromCharCode(65 + index)}. {answer.text}
                            </button>
                          ));
                        })()}
                      </div>
                      {selectedAnswer !== null && (
                        <div style={{ marginTop: '20px' }}>
                          <div 
                            style={{ 
                              padding: '15px', 
                              backgroundColor: (() => {
                                const currentQ = quizQuestions[currentQuizIndex];
                                if (!currentQ || selectedAnswer < 0) return '#fee2e2';
                                const randomizedAnswers = getRandomizedAnswers(currentQ);
                                return selectedAnswer < randomizedAnswers.length && randomizedAnswers[selectedAnswer]?.isCorrect ? '#dcfce7' : '#fee2e2';
                              })(),
                              border: `2px solid ${((): string => {
                                const currentQ = quizQuestions[currentQuizIndex];
                                if (!currentQ || selectedAnswer < 0) return '#ef4444';
                                const randomizedAnswers = getRandomizedAnswers(currentQ);
                                return selectedAnswer < randomizedAnswers.length && randomizedAnswers[selectedAnswer]?.isCorrect ? '#22c55e' : '#ef4444';
                              })()}`,
                              borderRadius: '8px',
                              marginBottom: '15px'
                            }}
                          >
                            <strong>{((): string => {
                              const currentQ = quizQuestions[currentQuizIndex];
                              if (!currentQ || selectedAnswer < 0) return '✗ Incorrect';
                              const randomizedAnswers = getRandomizedAnswers(currentQ);
                              return selectedAnswer < randomizedAnswers.length && randomizedAnswers[selectedAnswer]?.isCorrect ? '✓ Correct!' : '✗ Incorrect';
                            })()}</strong>
                            <p style={{ marginTop: '8px', fontSize: '14px' }}>
                              {quizQuestions[currentQuizIndex]?.explanation}
                            </p>
                          </div>
                          <button onClick={nextQuizQuestion} className="btn btn-primary" style={{ width: '100%' }}>
                            {currentQuizIndex < quizQuestions.length - 1 ? 'Next Question →' : 'See Results'}
                          </button>
                        </div>
                      )}
                    </div>
                  </>
                ) : (
                  <div className="card" style={{ textAlign: 'center', padding: '40px' }}>
                    <h3 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '20px' }}>
                      Quiz Complete! 🎉
                    </h3>
                    <p style={{ fontSize: '16px', color: '#6b7280', marginBottom: '20px' }}>
                      You've completed all {quizQuestions.length} questions.
                    </p>
                    <button onClick={restartQuiz} className="btn btn-primary">
                      Try Again
                    </button>
                  </div>
                )}
              </div>
            )}

            {(flashcards.length === 0 && quizQuestions.length === 0) && (
              <div className="card" style={{ textAlign: 'center', padding: '40px', backgroundColor: '#f8fafc' }}>
                <p style={{ color: '#6b7280' }}>
                  No study materials available for this note.
                </p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
